language: go

os:
- linux

env:
- GO111MODULE=on


install:
- pushd modules && make getdeps && popd

script:
- pushd modules && make verifiers && popd
- pushd modules && make coverage && popd
- pushd cmds && make && popd
- pushd tools && make && popd

after_success:
- pushd modules && bash <(curl -s https://codecov.io/bash)

go:
- '1.12.5'
