
@url = tfgrid.directory.node.2
node_id** = (S)
node_id_v1 = (S)
farm_id** = (I)
os_version** = (S)
#parameters = (dict)
created = (T)
updated = (T)
uptime = (I)
address = (S)
location = (O) !tfgrid.directory.location.1
total_resources = (O) !tfgrid.directory.node.resource.amount.1
used_resources = (O) !tfgrid.directory.node.resource.amount.1
reserved_resources = (O) !tfgrid.directory.node.resource.amount.1
proofs = (LO) !tfgrid.directory.node.proof.1
ifaces = (LO) !tfgrid.directory.node.iface.1
public_config = (O)!tfgrid.directory.node.public_iface.1
exit_node = (B)
approved = false (B)
public_key_hex = "" (S)     #hex representation of public key of the TF node
wg_ports = (LI)

#following info is not usable for provisioning, its convenience info for the farmer
#e.g. to know which interface names there are
#is only the physical interfaces where a cable is attached (INFO ONLY)
@url = tfgrid.directory.node.iface.1
name = (S)
addrs = (Liprange)
gateway = (Lipaddr)

#famer configures this information so we know how to configure the ipaddress
@url = tfgrid.directory.node.public_iface.1
master = (S) #physical interface name on which the vlan lives
type = "macvlan,vlan" (E)
ipv4 = (iprange)
ipv6 = (iprange)
gw4 = (ipaddr)
gw6 = (ipaddr)
version = (I)


@url = tfgrid.directory.node.resource.amount.1
cru** = (I)
mru** = (I)
hru** = (I)
sru** = (I)

@url = tfgrid.directory.node.proof.1
created = (T)
hardware_hash = (S)
disk_hash = (S)
hardware = (dict)
disks = (dict)
