

@url = tfgrid.workloads.reservation.container.1
#unique id inside the reservation is an autoincrement
workload_id = (I)
#links to unique node on the TFGrid
node_id = (S)
flist = (S)
hub_url = (S)
#env variables
environment = (dict)
#secret_env variables. the key is in plain text but the value
#must be encrypted using Curve25519 with the public key of node.
#then hex encoded.
secret_environment = (dict)
#the process to start
entrypoint = (S)
#corex yes or no
interactive = true (B)
volumes = (LO) !tfgrid.workloads.reservation.container.mount.1
network_connection = (LO) !tfgrid.workloads.reservation.network.connection.1
#where to send the statistics too
stats_aggregator = (LO) !tfgrid.workloads.reservation.statsaggregator.1
#id of threebot who is the farmer
farmer_tid = (I)
logs = (LO) !tfgrid.workloads.reservation.container.logs.1
capacity = (O) !tfgrid.workloads.reservation.container.capacity.1


@url = tfgrid.workloads.reservation.container.mount.1
volume_id = (S)
mountpoint = (S)

@url = tfgrid.workloads.reservation.network.connection.1
network_id = (S)
ipaddress = (ipaddress)
public_ip6 = (B)

@url = tfgrid.workloads.reservation.container.logs.1
type = (S)
data = (LO) !tfgrid.workloads.reservation.container.logsredis.1

@url = tfgrid.workloads.reservation.container.logsredis.1
stdout = (S)
stderr = (S)

@url = tfgrid.workloads.reservation.container.capacity.1
# Number of vCPU
cpu = (I)
# memory in MiB
memory = (I)
